import './globals.css';
import 'rc-unmodal/style.css';
import type { Metadata } from 'next';
import { GithubIcon } from '@/app/components/GithubIcon';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>
          <div className="bg-stone-50 w-screen min-h-screen">
            <div className="max-w-screen-lg mx-auto py-6 px-4 space-y-4">
              <div>
                <div className="flex items-start sm:flex-row sm:items-center justify-between gap-2">
                  <div>
                    <h1 className="text-2xl font-semibold">rc-unmodal</h1>
                    <div className="text-stone-600">A react component unified modal</div>
                  </div>
                  <div className="flex items-center gap-1">
                    <a
                      href="https://github.com/hunghg255/rc-unmodal"
                      target="_blank"
                      className="bg-black text-xs font-semibold text-white px-2.5 py-1 rounded-md inline-flex items-center hover:bg-black/80 transition-colors"
                    >
                      <GithubIcon className="size-4 mr-1" />
                      Github
                    </a>
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-[10px]">
                {/* <Link
                  href={'/'}
                  className="bg-black text-xs font-semibold text-white px-2.5 py-1 rounded-md inline-flex items-center hover:bg-black/80 transition-colors"
                >
                  Home
                </Link>

                <Link
                  href={'/documentation'}
                  className="bg-black text-xs font-semibold text-white px-2.5 py-1 rounded-md inline-flex items-center hover:bg-black/80 transition-colors"
                >
                  Documentation
                </Link> */}
              </div>

              <div>{children}</div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
